const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SUPABASE_URL='https://wcnmufiabeftlsregamh.supabase.co',SUPABASE_KEY='sb_publishable_FHlEZrROrCVM1WLdoij5Cw_7Ue64M1X';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'shiguang-quiz-auth'}});let user=null,questions=[],practiceQuestions=[],activeBank='中华文化题库',current=0,answered=false;
const titles={home:'总览',bank:'我的题库',practice:'开始刷题',wrong:'错题本'};
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(q,i){const legacy=q.options?.length===3&&q.options[0]&&q.options[1]&&q.options[2]&&(!q.answer||q.answer==='');return legacy?{...q,id:`${q.source}-${i}`,question:q.options[0],answer:'A',answerText:q.options[1],options:[],explanation:q.options[2],type:'single'}:{...q,id:`${q.source}-${i}`,question:q.question||'未命名题目',options:q.options?.length?q.options:['正确','错误'],answer:q.answer||'A',explanation:q.explanation||''}}
function enrichQuestions(list){const pool=list.map(q=>q.answerText||'').filter(Boolean);return list.map((q,i)=>{if(!q.answerText)return q;const wrong=[];for(let n=1;n<pool.length&&wrong.length<3;n++){const v=pool[(i+n*17)%pool.length];if(v!==q.answerText&&!wrong.includes(v))wrong.push(v)}const opts=[q.answerText,...wrong],shift=i%4,rot=opts.slice(shift).concat(opts.slice(0,shift));return {...q,options:rot,answer:String.fromCharCode(65+rot.indexOf(q.answerText))}})}
function showView(v){$$('.view').forEach(x=>x.classList.remove('active-view'));$`#${v}-view`?.classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent=titles[v]||titles.home;if(v==='wrong')renderReview();if(v==='practice')renderQuestion()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view);const bank=e.target.closest('[data-bank]');if(bank)selectBank(bank.dataset.bank)});
function bankName(q){return q.source&&(/港澳台|文化史|古代文化|pdf/i.test(q.source))?'中华文化题库':q.source||'未命名题库'}
function bankGroups(){const m={};questions.forEach(q=>{const n=bankName(q);(m[n]??=[]).push(q)});return m}
function card(name,qs){const isCulture=name==='中华文化题库';return `<article class="bank-card" data-bank="${esc(name)}"><div class="bank-top"><span class="book-icon blue">${isCulture?'文':'✦'}</span><span class="card-arrow">↗</span></div><h4>${esc(name)}</h4><small>${qs.length} 道题 · ${isCulture?'港澳台考研中华文化':'用户上传题库'}</small></article>`}
function renderBanks(){const groups=bankGroups(),names=Object.keys(groups),h=names.length?names.map(n=>card(n,groups[n])).join(''):'<div class="empty-state">题库正在加载。</div>';$('#home-banks').innerHTML=h;$('#all-banks').innerHTML=h;$('#bank-count').textContent=names.length;$('#bank-count-all').textContent=names.length;if($('#bank-total'))$('#bank-total').textContent=questions.length}
function selectBank(name){activeBank=name;const groups=bankGroups();practiceQuestions=(groups[name]||[]).filter(q=>!q.needsReview);current=0;renderQuestion();showView('practice');toast(`已选择：${name}`)}
function updateStats(){const h=read('practice-history'),total=h.reduce((n,x)=>n+(x.total||1),0),right=h.reduce((n,x)=>n+(x.correct??(x.score===100?1:0)),0);$('#total-answered').textContent=total;$('#accuracy').textContent=total?`${Math.round(right/total*100)}%`:'暂无';$('#recent-list').innerHTML=h.length?h.slice(-5).reverse().map(x=>`<div class="recent-row"><span class="mini-icon blue">◷</span><div><b>中华文化知识库</b><small>${x.time} · ${x.total} 题</small></div><span class="score">${x.score}<span>分</span></span></div>`).join(''):'<div class="empty-state">还没有练习记录，开始第一题吧。</div>'}
function renderReview(){const w=read('wrong-questions'),h=read('practice-history');$('#wrong-list').innerHTML=w.length?w.map(q=>`<div class="recent-row"><span class="mini-icon pink">⚑</span><div><b>${q.question}</b><small>答案：${q.answer||'见题目'} · ${q.explanation||'暂无解析'}</small></div></div>`).join(''):'<div class="empty-state">还没有错题，继续保持！</div>';$('#history-list').innerHTML=h.length?h.slice().reverse().map(x=>`<div class="recent-row"><span class="mini-icon blue">◷</span><div><b>中华文化知识库</b><small>${x.time} · ${x.total} 题</small></div><span class="score">${x.score}<span>分</span></div>`).join(''):'<div class="empty-state">完成一次练习后，这里会显示记录。</div>'}
function renderQuestion(){if(!practiceQuestions.length){$('#practice-card').innerHTML=`<div class="empty-state">“${esc(activeBank)}”暂无可直接练习的题目。请选择其他题库。</div>`;return}const q=practiceQuestions[current%practiceQuestions.length],fill=q.type==='fill',os=fill?[q.options[0],'与题意不符','资料未提及','以上都不对']:q.options,label=q.generatedOptions?'单选题 · 整理版选项':(fill?'填空题':q.type==='multiple'?'多选题':q.type==='judge'?'判断题':'单选题');if($('#practice-index'))$('#practice-index').textContent=`${current%practiceQuestions.length+1} / ${practiceQuestions.length}`;if($('#practice-meter'))$('#practice-meter').style.width=`${Math.round((current%practiceQuestions.length+1)/practiceQuestions.length*100)}%`;if($('#aside-meter'))$('#aside-meter').style.width=`${Math.round((current%practiceQuestions.length+1)/practiceQuestions.length*100)}%`;if($('#aside-progress'))$('#aside-progress').textContent=`第 ${current%practiceQuestions.length+1} 题，共 ${practiceQuestions.length} 题`;$('#practice-card').innerHTML=`<div class="question-meta"><span class="tag">${esc(activeBank)}</span><span>${label} · ${current%practiceQuestions.length+1} / ${practiceQuestions.length}</span></div><h3>${esc(q.question)}</h3><div class="options">${os.map((o,i)=>`<button data-i="${i}"><i>${String.fromCharCode(65+i)}</i> ${esc(o)}</button>`).join('')}</div><div class="answer-tip" id="answer-tip"></div><div class="explanation" id="explanation"></div><button class="next-btn" id="next-question">下一题 <span>→</span></button>`;answered=false;$$('.options button').forEach(b=>b.onclick=()=>answer(b,q,fill));$('#next-question').onclick=()=>{current++;renderQuestion()}}
async function answer(btn,q,fill){if(answered)return;answered=true;const exp=String(q.answer||'A').toUpperCase(),pick=String.fromCharCode(65+Number(btn.dataset.i)),ok=fill?Number(btn.dataset.i)===0:exp.includes(pick);btn.classList.add(ok?'selected':'wrong');$('#answer-tip').textContent=ok?'回答正确！继续保持 ✨':`回答错误，正确答案是 ${fill?q.options[0]:exp}`;$('#answer-tip').style.color=ok?'#58a879':'#df8065';$('#explanation').innerHTML=`<b>解析</b> ${esc(q.explanation||'原始题库未提供解析。')}<br><b>文化知识补充</b> ${q.needsReview?'该题来自扫描资料，建议对照原 PDF 校对。':'建议从时代背景、制度沿革、思想流派和代表人物建立关联。'}`;if(!ok){const w=read('wrong-questions');if(!w.some(x=>x.id===q.id))w.push(q);write('wrong-questions',w)}const h=read('practice-history');h.push({name:'中华文化知识库',time:new Date().toLocaleString('zh-CN'),total:1,correct:ok?1:0,score:ok?100:0});write('practice-history',h);updateStats();if(user&&db){await db.from('practice_history').insert({user_id:user.id,question_id:q.id,is_correct:ok});if(!ok)await db.from('wrong_questions').insert({user_id:user.id,question_id:q.id,question:q})}}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
if(location.protocol==='file:'&&$('#file-warning'))$('#file-warning').hidden=false;
async function importFile(file){const ext=file.name.toLowerCase().split('.').pop();try{let rows=[];if(['xlsx','xls'].includes(ext)&&window.XLSX){const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}else if(ext==='json'){rows=JSON.parse(await file.text());}else if(['csv','txt','md'].includes(ext)){const text=await file.text();rows=text.split(/\r?\n/).filter(Boolean).map((line,i)=>({question:line,options:['正确','错误'],answer:'A',explanation:'用户上传资料，待补充解析。',source:file.name,type:'single'}))}else{toast(`${file.name}：此格式需要服务端解析，未写入题库`);return}const imported=rows.map((r,i)=>{const v=normalize({source:file.name,type:r.type||'single',question:r.question||r['题目']||r['问题']||'',options:r.options||[r['选项A']||r.A||'正确',r['选项B']||r.B||'错误',r['选项C']||r.C||'',r['选项D']||r.D||''],answer:r.answer||r['答案']||'A',explanation:r.explanation||r['解析']||'用户上传资料，待补充解析。'},`upload-${Date.now()}-${i}`);return v});questions=questions.concat(imported);write('uploaded-questions',questions.filter(q=>q.source===file.name));renderBanks();renderQuestion();toast(`已导入 ${imported.length} 道题`)}catch(err){toast(`${file.name} 解析失败，请检查文件内容`)}}
$('#choose-file').onclick=()=>$('#file-input').click();$('#upload-trigger').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>[...e.target.files].forEach(importFile);const zone=$('#upload-zone');zone?.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('dragging')});zone?.addEventListener('dragleave',()=>zone.classList.remove('dragging'));zone?.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('dragging');[...e.dataTransfer.files].forEach(importFile)});
let authMode='login';function openAuth(){setAuthMode('login');$('#auth-modal').hidden=false;$('#auth-message').textContent=''}function closeAuth(){$('#auth-modal').hidden=true}function updateAuth(){const on=!!user;$('#auth-open').hidden=on;$('#auth-logout').hidden=!on;$('#profile-name').textContent=on?(user.user_metadata?.username||user.email?.split('@')[0]||'已登录用户'):'未登录';$('#profile-email').textContent=on?(user.email||user.phone||'已登录'):'登录后同步记录';if($('#page-title').closest('#home-view')?.classList.contains('active-view'))$('#page-title').textContent=on?`你好，${user.user_metadata?.username||user.email?.split('@')[0]||'同学'} 👋`:'总览'}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('#auth-title').textContent=signup?'注册拾光题库':'登录拾光题库';$('#auth-subtitle').textContent=signup?'注册后可用用户名、手机号或邮箱登录。':'使用邮箱、手机号或用户名登录。';$('#auth-submit').textContent=signup?'注册':'登录';$('#auth-switch').textContent=signup?'已有账号？登录':'没有账号？注册';$('#auth-divider-text').textContent=signup?'填写注册信息':'或使用账号密码';$('#auth-identifier').hidden=signup;$('#auth-username').hidden=!signup;$('#auth-phone').hidden=!signup;$('#auth-email').hidden=!signup;$('#auth-confirm').hidden=!signup;$('#google-auth').hidden=signup}
$('#auth-open').onclick=openAuth;$('#auth-close').onclick=closeAuth;$('#auth-switch').onclick=()=>setAuthMode(authMode==='login'?'signup':'login');
$('#google-auth').onclick=async()=>{if(!db)return $('#auth-message').textContent='登录服务暂不可用';$('#auth-message').textContent='正在前往 Google 登录…';const redirectTo=location.protocol==='file:'?'https://teslacui.github.io/shiguang-quiz/':location.origin+location.pathname;const r=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(r.error)$('#auth-message').textContent=`Google 登录失败：${r.error.message}`};
$('#auth-submit').onclick=async()=>{if(!db)return $('#auth-message').textContent='登录服务暂不可用';const password=$('#auth-password').value;if(password.length<6)return $('#auth-message').textContent='密码至少需要 6 位';if(authMode==='signup'){const username=$('#auth-username').value.trim(),phone=$('#auth-phone').value.trim(),email=$('#auth-email').value.trim(),confirm=$('#auth-confirm').value;if(!username||username.length<2)return $('#auth-message').textContent='请输入至少 2 个字符的用户名';if(!email||!email.includes('@'))return $('#auth-message').textContent='请输入有效邮箱';if(password!==confirm)return $('#auth-message').textContent='两次输入的密码不一致';const r=await db.auth.signUp({email,password,options:{data:{username,phone}}});if(r.error){const m=r.error.message.toLowerCase();$('#auth-message').textContent=m.includes('rate limit')?'注册邮件发送过于频繁，请等待一段时间后再试，或使用已有账号登录。':r.error.message}else{user=r.data.user;closeAuth();updateAuth();toast('注册成功，请查收验证邮件')}}else{const identifier=$('#auth-identifier').value.trim();if(!identifier)return $('#auth-message').textContent='请输入用户名、手机号或邮箱';let credentials;if(identifier.includes('@'))credentials={email:identifier,password};else if(/^\+?[0-9\- ]{7,}$/.test(identifier))credentials={phone:identifier.replace(/[\- ]/g,''),password};else{const lookup=await db.from('profiles').select('email').eq('username',identifier).maybeSingle();if(lookup.error||!lookup.data?.email)return $('#auth-message').textContent='未找到该用户名，请检查后重试';credentials={email:lookup.data.email,password}}const r=await db.auth.signInWithPassword(credentials);if(r.error)$('#auth-message').textContent=r.error.message;else{user=r.data.user;closeAuth();updateAuth();await syncUserData();toast('登录成功')}}};
$('#auth-logout').onclick=async()=>{if(db)await db.auth.signOut();user=null;updateAuth();toast('已退出登录')};$('#clear-wrong').onclick=()=>{write('wrong-questions',[]);renderReview();toast('已清空错题本')};
async function syncUserData(){if(!user||!db)return;const [h,w]=await Promise.all([db.from('practice_history').select('*').eq('user_id',user.id).order('answered_at',{ascending:true}),db.from('wrong_questions').select('*').eq('user_id',user.id)]);if(!h.error&&h.data?.length){write('practice-history',h.data.map(x=>({name:'中华文化知识库',time:new Date(x.answered_at).toLocaleString('zh-CN'),total:1,correct:x.is_correct?1:0,score:x.is_correct?100:0})));updateStats()}if(!w.error&&w.data?.length)write('wrong-questions',w.data.map(x=>x.question));renderReview()}
async function ensureProfile(){if(!user||!db||!user.email)return;const p=user.user_metadata||{};if(p.username)await db.from('profiles').upsert({user_id:user.id,username:p.username,phone:p.phone||'',email:user.email},{onConflict:'user_id'})}
async function handleAuthSubmit(){if(!db)return $('#auth-message').textContent='登录服务暂不可用';const password=$('#auth-password').value;if(password.length<6)return $('#auth-message').textContent='密码至少需要 6 位';if(authMode==='signup'){const username=$('#auth-username').value.trim(),phone=$('#auth-phone').value.trim(),email=$('#auth-email').value.trim(),confirm=$('#auth-confirm').value;if(!username||username.length<2)return $('#auth-message').textContent='请输入至少 2 个字符的用户名';if(!email||!email.includes('@'))return $('#auth-message').textContent='请输入有效邮箱';if(password!==confirm)return $('#auth-message').textContent='两次输入的密码不一致';const r=await db.auth.signUp({email,password,options:{data:{username,phone}}});if(r.error){const m=r.error.message.toLowerCase();$('#auth-message').textContent=m.includes('rate limit')?'注册邮件发送过于频繁，请稍后再试。也可以直接使用已有账号登录。':r.error.message}else{closeAuth();toast('注册成功，请查收验证邮件')}}else{const identifier=$('#auth-identifier').value.trim();if(!identifier)return $('#auth-message').textContent='请输入用户名、手机号或邮箱';let email=identifier;if(!identifier.includes('@')){const lookup=await db.rpc('lookup_login_email',{p_identifier:identifier});if(lookup.error||!lookup.data)return $('#auth-message').textContent='未找到该用户名或手机号，请检查后重试';email=lookup.data}const r=await db.auth.signInWithPassword({email,password});if(r.error)$('#auth-message').textContent=r.error.message;else{user=r.data.user;closeAuth();updateAuth();await ensureProfile();await syncUserData();toast('登录成功')}}}
$('#auth-submit').onclick=handleAuthSubmit;
renderBanks();renderReview();updateStats();fetch('questions.json').then(r=>r.ok?r.json():[]).then(x=>{questions=enrichQuestions(x.map(normalize)).concat(read('uploaded-questions'));const groups=bankGroups();activeBank=groups['中华文化题库']?'中华文化题库':Object.keys(groups)[0]||'中华文化题库';practiceQuestions=(groups[activeBank]||[]).filter(q=>!q.needsReview);renderBanks();renderQuestion();updateStats()}).catch(()=>renderQuestion());if(db)db.auth.getSession().then(async r=>{user=r.data.session?.user||null;updateAuth();await ensureProfile();await syncUserData()});else updateAuth();
if(db)db.auth.onAuthStateChange(async(_event,session)=>{if(session){user=session.user;await ensureProfile();updateAuth()}});
