-- 拾光题库 Supabase 建表脚本（幂等，可整段重复执行）
-- 说明：create policy 不支持 IF NOT EXISTS，故先 DROP POLICY IF EXISTS 再建，
--       表均用 create table if not exists，不会覆盖已有数据。

create table if not exists practice_history (id bigint generated by default as identity primary key,user_id uuid references auth.users not null,question_id text not null,is_correct boolean not null,answered_at timestamptz default now());
create table if not exists wrong_questions (id bigint generated by default as identity primary key,user_id uuid references auth.users not null,question_id text not null,question jsonb not null,created_at timestamptz default now());
create unique index if not exists wrong_questions_user_question_idx on wrong_questions(user_id,question_id);
create table if not exists profiles (user_id uuid primary key references auth.users on delete cascade,username text unique not null,phone text,email text unique not null,created_at timestamptz default now());
alter table practice_history enable row level security; alter table wrong_questions enable row level security;
alter table profiles enable row level security;
drop policy if exists "own history" on practice_history;
create policy "own history" on practice_history for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own wrong questions" on wrong_questions;
create policy "own wrong questions" on wrong_questions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own profile" on profiles;
create policy "own profile" on profiles for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create or replace function lookup_login_email(p_identifier text) returns text language sql security definer set search_path=public as $$ select email from profiles where lower(username)=lower(trim(p_identifier)) or regexp_replace(coalesce(phone,''),'[^0-9+]','','g')=regexp_replace(trim(p_identifier),'[^0-9+]','','g') limit 1 $$;
revoke all on function lookup_login_email(text) from public;
grant execute on function lookup_login_email(text) to anon,authenticated;

-- 用户学习状态（遗忘曲线调度）。建表后可跨设备同步复习计划。
create table if not exists review_state (user_id uuid references auth.users not null,question_id text not null,box int not null default 0,due_at timestamptz,wrong int not null default 0,ok_count int not null default 0,updated_at timestamptz default now(),primary key (user_id,question_id));
alter table review_state enable row level security;
drop policy if exists "own review state" on review_state;
create policy "own review state" on review_state for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create index if not exists review_state_user_due_idx on review_state(user_id,due_at);

-- 练习会话记录（进入->退出为一次），用于主页累计答题/正确率/打卡统计。
create table if not exists practice_sessions (id bigint generated always as identity primary key,user_id uuid references auth.users not null,bank text not null default '中华文化知识库',started_at timestamptz not null,ended_at timestamptz not null,duration_sec int not null default 0,q_count int not null default 0,correct int not null default 0,created_at timestamptz default now());
alter table practice_sessions enable row level security;
drop policy if exists "own practice sessions" on practice_sessions;
create policy "own practice sessions" on practice_sessions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create index if not exists practice_sessions_user_start_idx on practice_sessions(user_id,started_at);
