create table if not exists practice_history (id bigint generated by default as identity primary key,user_id uuid references auth.users not null,question_id text not null,is_correct boolean not null,answered_at timestamptz default now());
create table if not exists wrong_questions (id bigint generated by default as identity primary key,user_id uuid references auth.users not null,question_id text not null,question jsonb not null,created_at timestamptz default now());
alter table practice_history enable row level security; alter table wrong_questions enable row level security;
create policy "own history" on practice_history for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "own wrong questions" on wrong_questions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
